config/routes.rb
Dd::Application.routes.draw do


scope "(:locale)", locale: /ru|en/ do


  match '/ad', to: 'users#signin', via: :get

  resources :users do
    collection do
      get :signin
      post :signin, action: 'check'
      get :signout
    end
  end

  match '/news', to: 'news/feeds#list', via: :get #admin list of news
  
  namespace 'news' do
    resources :feeds do
      collection {get :tags}
      collection {post :tags_update}
      collection {post :insert_media}
    end
  end
 

  root to: 'pages#home'

  match '/help', to: 'pages#help', via: :get  #site
  match '/translation', to: 'pages#translation', via: :get  #admin
  match '/update_translation', to: 'pages#update_translation', via: :post  #admin

  match '/browser_detect', to: 'pages#browser_detect', via: :get #site
  match '/help_edit', to: 'pages#help_edit', via: :get  #admin
  match '/help_update', to: 'pages#help_update', via: [:put, :post] #admin
  match '/home_update', to: 'pages#home_update', via: [:post, :put] #admin
  match '/home_edit', to: 'pages#home_edit', via: :get  #admin


  match '/albom_c', to: 'alboms#gallery', via: :get #site
  match '/member_c', to: 'members_page#show', via: :get #site
  match '/concert_c', to: 'concerts#show', via: :get #site

  match '/concerts/alboms', to: 'concerts#alboms', via: :get #admin
  match '/concerts/members', to: 'concerts#members', via: :get #admin
  match '/concerts/partners', to: 'concerts#partners', via: :get #admin
  
  match '/update', to: 'alboms#update' #adim

  match 'home/:id', to: 'pages#home', as: :ura  #site, cycle by year in home page


resources :mailics do
  collection {post :captcha}
  collection {post :volunteer}
  collection {post :callback}
end


resources :flags, only: [:index, :create]

  # match 'contacts' =>       'contacts#index'
  # match 'contacts/edit' =>  'contacts#edit'
  # match 'contacts/creat' => 'contacts#creat', via: post
  # match 'contacts/text' =>  'contacts#tetx', via: post

  resources :contacts, only: [:index, :create, :edit] do
    collection {post :text}
    collection {get :edit}
  end

  resources :teams  #team of project

  resources :concerts do
    member {post :m_update}
    resources :members_page, only: [:show, :edit, :update] do #because has_one
      collection {get :page}
    end
    
    resources :carousels
    resources :members  #members each concert

    resources :partners do
      collection {post :global} # update who is for home page
    end

    resources :alboms do
      collection {get :gallery}
    end
    resources :videos
  end

  resources :fotos

end
end

app/models/albom.rb
#encoding: UTF-8
class Albom < ActiveRecord::Base

  attr_accessible :fotos_attributes, :fototitle
  attr_accessible :text, :title, :tumba, :mainfoto
  translates :text, :title, :tumba
  belongs_to :concert
  has_many :fotos, dependent: :destroy
  has_attached_file :fototitle, styles: {original: "433x350>", gallery: "280x247>", sm: "64x64>"}, default_style: :gallery #280x247
  validates :text, presence: { message: 'Отсутствует текстовая часть' }
  validates :title, presence: { message: 'Отсутствует заглавие' }
  validates :tumba, presence: { message: 'Отсутствует тумба' }

  accepts_nested_attributes_for :fotos
  default_scope order('id DESC')


  def url(arg = :original)
    fototitle.url(arg)
  end

  def year_title
    concert.year.to_s + ' ' + title
  end

  def next
    if concert.alboms.first == self
      concert.alboms.last
    else
      concert.alboms.where('id > ?', id).last
    end
  end

  def prev
    if concert.alboms.last == self
      concert.alboms.first
    else
      concert.alboms.where('id < ?', id).first
    end
  end


  def fotos_attributes=(att)
  	# debugger
    att.each do |i|
    	fotos.build(image: i)
    end
  end

end

app/controllers/alboms_controller.rb
#encoding: UTF-8
class AlbomsController < ApplicationController
  before_filter :signed_in_user,  except: [:gallery, :show]


  layout 'dd', only: [:gallery, :show]

  def index
    @concert = Concert.find params[:concert_id]
    @alboms = @concert.alboms
  end

  def gallery #main link in home
    @concert = Concert.last_not_annoucement params[:concert_id]
    @center = params[:center].blank? ? @concert : Concert.find(params[:center])
    @alboms = @concert.alboms
    @videos = @concert.videos
    @url_to_edit = concert_alboms_path(@concert)
    respond_to do |f|
      f.html
      f.js {}
    end
  end
  
  def show
    @albom = Albom.find(params[:id])
    @url_to_edit = edit_concert_albom_path

  end

  def new
    #debugger
    @albom = Concert.find(params[:concert_id]).alboms.build

  end

  def edit
    @albom = Albom.find(params[:id])
  end

  def create
     # debugger

    @albom = Concert.find(params[:concert_id]).alboms.build(params[:albom])

    if @albom.save
      redirect_to edit_concert_albom_path(@albom.concert, @albom), notice: 'Альбом успешно создан'
    else
      render action: "new"
    end
  end

  def update
    notice = nil
    @albom = Albom.find(params[:id])
    if params.key? 'ChooseImage'
      if params.key?(:albom) && params[:albom].key?(:dels_attributes)
        #debugger
        @albom.mainfoto = params[:albom][:dels_attributes].first
        debugger
        @albom.fototitle = @albom.fotos.find(@albom.mainfoto).image
        notice = "Выбрана обложка #{@albom.fotos.find(@albom.mainfoto).image_file_name}" if @albom.save
      else
        notice = "Не выбрано ни одно фото"
      end
    elsif params.key? 'UploadImage'
      if params.key?(:albom) && params[:albom].key?(:fotos_attributes)
        params[:albom][:fotos_attributes].each{ |i| @albom.fotos.build(image: i) }
        notice = "Фото подгружены, (#{params[:albom][:fotos_attributes].size} шт.)" if @albom.save
      else
        notice = "Ничего не подгружено"
      end
    elsif params.key? 'DeleteImage'
      if params.key?(:albom) && params[:albom].key?(:dels_attributes)
        params[:albom][:dels_attributes].each{ |i| Foto.find(i).destroy }
        notice = "Фото удалены (#{params[:albom][:dels_attributes].size} шт.)"
      else
        notice = "Ничего не удалено"
      end
    elsif params.key? 'UploadText'
      notice = 'Альбом успешно обновлен' if @albom.update_attributes(params[:albom])
    end

    if notice
      redirect_to edit_concert_albom_path(@albom.concert, @albom), notice: notice
    else
      render action: "edit"
    end
  end

  def destroy
    @albom = Albom.find(params[:id])
    
    redirect_to concert_alboms_url, notice: "Удален #{@albom.destroy.title}"
  end
end

app/helpers/alboms_helper.rb
module AlbomsHelper
end

app/views/alboms/_albom.html.erb

<%= raw '<div class="row">' if albom_counter % 3 == 0 %>
  <div class="t-box-3 album-thumb">
    <%= link_to [albom.concert, albom] do %>
      <%= image_tag albom.fototitle.url %>
      <span class="album-mask">
        <h6><span></span><%= albom.title %></h6>
        <p><%= albom.tumba %></p>
      </span>
    <% end %>
  </div>
<%= raw '</div>' if albom_counter % 3 == 2 %>

app/views/alboms/_form.html.erb
<%= render partial: 'template/error', object: @albom %>
<%= form_for [@albom.concert, @albom] do |f| %>  

  <div>
    <div style="display:inline-block;">
      <div class="field">
        <%= f.label :title, "Заглавие" %><br />
        <%= f.text_field :title, size: 91 %>
      </div>
      <br/>
      <div class="field">
        <%= f.label :text, "Текст" %><br />
        <%= f.text_area :text, rows_by_cols_and_content( @albom.text, 70) %>
      </div>
      <br/>
      <div class="field">
        <%= f.label :tumba, "Тумбочка" %><br />
        <%= f.text_area :tumba, rows_by_cols_and_content( @albom.tumba, 70) %>
      </div>
      <div class="actions">
        <%= f.submit 'Обновить текстовую информацию', name: "UploadText" %>
      </div>
    </div>
    <div style="display:inline-block;margin-left:12px">
      <%= image_tag(@albom.fototitle.url) if @albom.fototitle.exists? %>
    </div>
  </div>

<% end %>
<%= render('fotos') if @albom.persisted? %>

app/views/alboms/_fotos.html.erb
<div class='bottom_line' style="margin-bottom:6px"></div>

<%= form_for [@albom.concert, @albom], multipart: true do |f2| %>
  <div class="field" style='float:left;width:250px'>
    <%= f2.label 'fotos_attributes', 'Выбрать фоточки'%>
    <%= f2.file_field 'fotos_attributes', accept: 'image/*', multiple: true %>
  </div>
  <div class="actions">
    <%= f2.submit 'Загрузить на сервер', name: 'UploadImage', style: 'width: 155px' %>
    <%= f2.submit 'Назначить обложку', name: 'ChooseImage', style: 'width: 155px' %>
    <br/>
    <%= f2.submit 'Удалить выбранное', name: 'DeleteImage', style: 'width: 155px' %>
  </div>


  <div style='clear:both'></div>

  <div class='fotos'>
    <% @albom.fotos.each do |foto| %>
      <div class='foto' <%= "id=mainfoto" if foto.id == @albom.mainfoto %>>
        <span class='fotospan'> 
          <div>
            <%= image_tag foto.image.url(:sm) %>
            <%= check_box_tag 'albom[dels_attributes][]', foto.id, false, hidden:true %>
          </div>
        </span>
      </div>
    <% end %>
  </div>

<% end %>

<div style='clear: both'></div>

<script>
  $('input[name=UploadImage').click(function(){ $('#notice').text('...идет загрузка изображений'); });
  $('input[name=ChooseImage').click(function(){ $('#notice').text('...подождите секундочку...'); });
  $('.foto').click(function(){
    $(this).find('input')[0].checked = $(this).find('input')[0].checked == 1 ? 0: 1 
    $(this).toggleClass('hru');
  });
</script>
<style>
.foto{
  float: left;
}
#mainfoto{
  background: green;
}
input[name=DeleteImage]{
  background: red;
  font-weight: 700;
  border-color: red;
}
input[name=DeleteImage]:hover{
  border-color: #999;
  background: #f33;
}
.fotospan{
  height: 70px;
  width: 70px;
  border: 1px #eee solid;
  display: table-cell;
  text-align: center; 
  vertical-align: middle;
}
.foto:hover{
  background: blue;
}
.hru:hover{
  background: yellow;
}
.fotospan:hover{
  border: 1px blue solid;
  /*background: blue;*/
}
.hru{
  background: red;
}
.fotospan:hover img{
  border: 2px solid white;
}
.foto img {
  display: inline;
  vertical-align: middle;
}
</style>

app/views/alboms/_paginator_bottom.html.erb
<div class="wrap-paginatior">
        <div class="inner-space">
          <div class="navigation">
            <ul>
              <li class="prev">
                <%= link_to "", concert_albom_path(@albom.concert, @albom.prev) %>
              </li>
              <li class="back">
                <%= link_to "", gallery_concert_alboms_path(@albom.concert) %>
              </li>
              <li class="next">
                <%= link_to "", concert_albom_path(@albom.concert, @albom.next) %>
              </li>
            </ul>
          </div>
        </div>
      </div>

app/views/alboms/_video2.html.erb
<% debugger %>
<%= raw '<div class="row">' if video_counter % 3 == 0 %>
  <div class="t-box-3 album-thumb">
    <%= link_to video.link, rel: :youtube, class: 'swipebox-video hover-video' do %>
      <%= image_tag video.foto.url %>
      <span class="video-mask"></span>
    <% end %>
  </div>
<%= raw '</div>' if video_counter % 3 == 2 %>

app/views/alboms/edit.html.erb
<% content_for :lnks2 do %>
  | <%= link_to 'К концерту', edit_concert_path %>
  | <%= link_to 'К списку', concert_alboms_path %>
  | <%= link_to 'Новый', :new_concert_albom, data: {confirm: 'Несохраненные данные будут утеряны, Да ?'} %>
  | <%= link_to 'Удалить', concert_albom_path(@albom.concert, @albom), method: :delete, data: { confirm: 'Вы уверены что хотите удалить данного участника ? Он хороший.' } %>
  | <%= link_to_function 'Записать текст', "$('input[name=UploadText]').first().click()" %>
  | <%= link_to_function 'Загрузить фото', "$('input[name=UploadImage]').first().click()" %>
  | <%= link_to_function 'Выбрать обложку', "$('input[name=ChooseImage]').first().click()" %>
  | <%= link_to_function 'Удалить фото', "$('input[name=DeleteImage]').first().click()" %>
  | <%= link_to '0', concert_albom_path, title: 'Просмотр' %>
  |
<% end %>

<%= h1andcontent "Альбом #{@albom.title}, #{@albom.concert.year}" %>

<%= render 'form' %>

app/views/alboms/gallery.html.erb
<% provide(:title, t('global.title')) %>

<div class="gallery-content">
  <div class="container">
    <div class="top-info-content">
      <div class="inner-space">
        <h1><%= t 'gallery.title' %></h1>
      </div>
      <div class="triangle-gray-up"></div>
    </div>
    <div class="p-gallery">

      <div class="inner-space">

        <div class="nav-gallery-year">
          <ul>
            <%= render partial: 'template/top_paginator', locals: {in_path: :gallery_concert_alboms_path} %>
          </ul>
        </div>

        <% unless @alboms.empty? %>
          <h1><%= t 'gallery.fotoalbom' %></h1>
          <div class="album-thumbs">
            <div class="album-thumbs">
              <%= render @alboms %>
              <%= raw '</div>' if @alboms.count % 3 != 2 %>
            </div>
          </div>
        <% end %>

      </div>

      <div class="video-thumbs">
        <div class="triangle-gray-down"></div>
        
        <% unless @videos.empty? %>
          <h1><%= t 'gallery.video' %></h1>
          <div class="inner-space">
            <%= render @videos %>
            <%= raw '</div>' if @videos.count % 3 != 2 %>
          </div>
        <% end %>
        
        <div class="triangle-gray-up"></div>
      </div>

      <%= render '/template/bottom_paginator', in_next: gallery_concert_alboms_path(@concert.next), in_prev: gallery_concert_alboms_path(@concert.prev) %>

    </div>
  </div>
</div>

app/views/alboms/gallery.js.erb

$('.nav-gallery-year ul').first().html("<%= escape_javascript(render(partial: 'template/top_paginator', locals: {in_path: :gallery_concert_alboms_path})) %>");

app/views/alboms/index.html.erb
<% content_for :lnks2 do %>
  | <%= link_to 'К концерту', edit_concert_path(@concert) %>
  | <%= link_to 'Новый', new_concert_albom_path %>
  | <%= link_to 'Видео', concert_videos_path(@concert) %>
  | <%= link_to '0', gallery_concert_alboms_path(@concert), title: 'Просмотр' %>
  |
<% end %>
<%= h1andcontent "Список альбомов (#{@alboms.count}), #{@concert.year}" %>


<table>
  <% @alboms.each do |albom| %>
    <tr>
      <td width='68px' height='68px' align='center'>
        <%= image_tag albom.fototitle.url(:sm) %>
      </td>
      <td style="width:333px;padding-left:6px;font-size:16px">
        <%= albom.title %>
      </td>
      <td>
        <%= link_to 'Просмотр', [@concert, albom] %><br/>
        <%= link_to "Изменить (#{albom.fotos.count})", edit_concert_albom_path(@concert, albom) %><br/>
        <%= link_to 'Удалить', [@concert, albom], method: :delete, data: { confirm: 'Вы уверены в том, чтобы удалить данный альбом ?' } %>
      </td>
    </tr>
  <% end %>
</table>

app/views/alboms/new.html.erb
<% content_for :lnks2 do %>
  | <%= link_to 'К концерту', edit_concert_path(@albom.concert) %>
  | <%= link_to 'К списку', concert_alboms_path %>
  | <%= link_to_function 'Записать текст', "$('input[name=UploadText]').first().click()" %>
  | <%= link_to '0', :root, title: 'Просмотр' %>
  |
<% end %>

<%= h1andcontent "Новый альбом, #{@albom.concert.year}" %>

<%= render 'form' %>

app/views/alboms/show.html.erb
<% provide(:title, t('global.title')) %>

<div class="gallery-content">
  <div class="container">
    <div class="top-info-content">
      <div class="inner-space">
        <%= content_tag :h2, @albom.title %>
      </div>
      <div class="triangle-gray-up"></div>
    </div>
    <div class="p-gallery-inner">
      <div class="gallery-description">
        <div class="inner-space">
          <p>
            <%= @albom.text %>
          </p>
        </div>
      </div>
      <div class="gi-content">

        <div class="triangle-gray-down"></div>
        <div class="inner-space">

          <div class="gi-thumbs">
          
            <% @albom.fotos.each do |f| %>
              <div class="gi-thumb">
                <%= link_to f.image.url, class: :swipebox do %>
                  <%= image_tag f.image.url(:gallery) %>
                  <span class="img-mask"></span>
                <% end %>
              </div>
            <% end %>

          </div>

        </div>
        
        <div class="triangle-gray-up"></div>
      </div>

      <%= render 'paginator_bottom' %>

    </div>
  </div>
</div>

app/views/alboms/show22.html.erb
<% content_for :lnks2 do %>
  | <%= link_to 'К списку', concert_alboms_path %>
  | <%= link_to 'Новый', :new_concert_albom %>
  | <%= link_to 'Изменить', :edit_concert_albom %>
  | <%= link_to 'Удалить', concert_albom_path(@albom.concert, @albom), method: :delete, data: { confirm: 'Вы уверены что хотите удалить данного участника ? Он хороший.' } %>
  |
<% end %>

<div style='font-family:arial;font-size:16px'>
  <p>
    <%= @albom.title %>
  </p>
  <div style="display:inline-block;margin-left:12px">
    <%= image_tag(@albom.fototitle.url) if @albom.fototitle.exists? %>
  </div>
  <div style="width:333px;display:inline-block;">
    <div>
      <%= @albom.text %>
    </div>
  </div>

  <p>
    <%= @albom.tumba %>
  </p>
</div>



<% @albom.fotos.each do |foto| %>
  <%= image_tag foto.image.url(:sm) %>
<% end %>