config/routes.rb
Dd::Application.routes.draw do


scope "(:locale)", locale: /ru|en/ do


  match '/ad', to: 'users#signin', via: :get

  resources :users do
    collection do
      get :signin
      post :signin, action: 'check'
      get :signout
    end
  end

  match '/news', to: 'news/feeds#list', via: :get #admin list of news
  
  namespace 'news' do
    resources :feeds do
      collection {get :tags}
      collection {post :tags_update}
      collection {post :insert_media}
    end
  end
 

  root to: 'pages#home'

  match '/help', to: 'pages#help', via: :get  #site
  match '/translation', to: 'pages#translation', via: :get  #admin
  match '/update_translation', to: 'pages#update_translation', via: :post  #admin

  match '/browser_detect', to: 'pages#browser_detect', via: :get #site
  match '/help_edit', to: 'pages#help_edit', via: :get  #admin
  match '/help_update', to: 'pages#help_update', via: [:put, :post] #admin
  match '/home_update', to: 'pages#home_update', via: [:post, :put] #admin
  match '/home_edit', to: 'pages#home_edit', via: :get  #admin


  match '/albom_c', to: 'alboms#gallery', via: :get #site
  match '/member_c', to: 'members_page#show', via: :get #site
  match '/concert_c', to: 'concerts#show', via: :get #site

  match '/concerts/alboms', to: 'concerts#alboms', via: :get #admin
  match '/concerts/members', to: 'concerts#members', via: :get #admin
  match '/concerts/partners', to: 'concerts#partners', via: :get #admin
  
  match '/update', to: 'alboms#update' #adim

  match 'home/:id', to: 'pages#home', as: :ura  #site, cycle by year in home page


resources :mailics do
  collection {post :captcha}
  collection {post :volunteer}
  collection {post :callback}
end


resources :flags, only: [:index, :create]

  # match 'contacts' =>       'contacts#index'
  # match 'contacts/edit' =>  'contacts#edit'
  # match 'contacts/creat' => 'contacts#creat', via: post
  # match 'contacts/text' =>  'contacts#tetx', via: post

  resources :contacts, only: [:index, :create, :edit] do
    collection {post :text}
    collection {get :edit}
  end

  resources :teams  #team of project

  resources :concerts do
    member {post :m_update}
    resources :members_page, only: [:show, :edit, :update] do #because has_one
      collection {get :page}
    end
    
    resources :carousels
    resources :members  #members each concert

    resources :partners do
      collection {post :global} # update who is for home page
    end

    resources :alboms do
      collection {get :gallery}
    end
    resources :videos
  end

  resources :fotos

end
end

app/models/carousel.rb
#encoding: UTF-8
class Carousel < ActiveRecord::Base
  belongs_to :concert
  belongs_to :foto
  belongs_to :video

  NUMBER = %w{ незвестна заглавная второстепенная }

  attr_accessible :number, :show_index, :foto_id, :video_id

  default_scope order('show_index ASC')
  scope :firstCarousel, where('number = 1').order('show_index ASC')
  scope :secondCarousel, where('number = 2').order('show_index ASC')


  def url (arg = nil)
    foto_id ? foto.image.url(arg) : video_id ? video.foto.url(arg) : nil
  end

  def video_or_foto s1, s2 = ''
    video_id ? s1 : s2    
  end
  
end

app/controllers/carousels_controller.rb
#encoding: UTF-8
class CarouselsController < ApplicationController
  before_filter :signed_in_user

  # layout 'dd', only: [:gallery, :show]

  def index
    @concert = Concert.find params[:concert_id]
    @videos = @concert.videos
    @alboms = @concert.alboms.includes(:fotos)
  end

  
  def show
    # @carousel = carousel.find(params[:id])
  end

  def new
    @concert = Concert.find params[:concert_id]
    @alboms = @concert.alboms.includes(:fotos)
    @videos = @concert.videos
    @carousel = Concert.find(params[:concert_id]).carousels.build
  end

  def edit
    @concert = Concert.find params[:concert_id]
    @alboms = @concert.alboms.includes(:fotos)
    @videos = @concert.videos
    @carousel = Concert.find(params[:concert_id]).carousels.build
  end

  def create
    @concert = Concert.find params[:concert_id]
    @alboms = @concert.alboms.includes(:fotos)
    @videos = @concert.videos
    @carousel = Concert.find(params[:concert_id]).carousels.build
    @concert.carousels.where(params[:carousel]).create( params[:new] )
    @concert.carousels.delete( Carousel.find params[:del] ) if params[:del]

    redirect_to concert_carousels_path(@concert, params[:carousel]), notice: 'Карусел успешно обновлен'

    rescue
      redirect_to concert_carousels_path(@concert, params[:carousel]), notice: 'Что-то пошло не так гладко'
  end

  def update

  end

  def destroy

  end
end

app/views/carousels/_form.html.erb

<%= link_to concert_alboms_path(@concert) do %> 
  <span class='header'>Альбомы</span>
<% end %>

<%= form_for concert_carousels_path(@concert) do |f| %>  
  <%= hidden_field :carousel, :number, value: params[:number]  %>
  <div>
    <% @alboms.each do |a| %>
      <br/>
      <%= link_to edit_concert_albom_path(@concert, a) do %> 
        <%= a.title %>
      <% end %>

      <br/>
      <%= render partial: 'fotos', locals: {albom: a} %>
    <% end %>
  </div>
  <br/>

  <%= link_to concert_videos_path(@concert) do %> 
    <span class='header'>Видео</span>
  <% end %>
  <%= render 'video' %>

  <br/>

  <div class="actions">
    <%= submit_tag 'Установить' %>
  </div>

<% end %>





<script>
  $('.fotospan').click(function(){
    $(this).find('input')[0].checked = $(this).find('input')[0].checked - 1
    $(this).toggleClass('hru');
  });
</script>
<style>
.header{
  font-size: 22px;
  padding-left: 16px;
}
.fotos{
  width: 70%;
}
.foto{
  float: left;
}
.foto:hover{
  background: blue;
}

.foto img {
  display: inline;
  vertical-align: middle;
}
#in_carousel{
  background: #7b7;
}
.fotospan:hover{
  border: 1px blue solid;
  /*background: blue;*/
}
.fotospan:hover img{
  border: 2px solid white;
}
.hru:hover{
  background: yellow;
}
#in_carousel.hru{
  background: red;
}
.hru{
  background: #f57;
}
input[name=DeleteImage]{
  background: red;
  font-weight: 700;
  border-color: red;
}
input[name=DeleteImage]:hover{
  border-color: #999;
  background: #f33;
}
.fotospan{
  height: 72px;
  width: 72px;
  border: 1px #eee solid;
  display: table-cell;
  text-align: center; 
  vertical-align: middle;
}

</style>

app/views/carousels/_fotos.html.erb
<div style='clear:both'></div>

<div class='fotos'>
  <% albom.fotos.each do |foto| %>
    <% flag = @concert.carousels.where(number: params[:number]).find_by_foto_id(foto.id) %>
    <div class='foto'>
      <span class='fotospan' <%= "id=in_carousel" if flag %> > 
        <div>
          <%= image_tag foto.image.url(:sm) %>
          <%= check_box_tag (flag ? '[del][]' : '[new][][foto_id]'), flag ? flag.id : foto.id, false, hidden:true %>
        </div>
      </span>
    </div>
  <% end %>
</div>

<div style='clear: both'></div>

app/views/carousels/_video.html.erb
<div style='clear:both'></div>

<div class='fotos'>
  <% @concert.videos.each do |video| %>
    <% flag = @concert.carousels.where(number: params[:number]).find_by_video_id(video.id) %>
    <div class='foto'>
      <span class='fotospan' <%= "id=in_carousel" if flag %> > 
        <div>
          <%= image_tag video.foto.url(:sm) %>
          <%= check_box_tag (flag ? '[del][]' : '[new][][video_id]'), flag ? flag.id : video.id, false, hidden:true %>
        </div>
      </span>
    </div>
  <% end %>
</div>

<div style='clear: both'></div>

app/views/carousels/index.html.erb
#encoding: UTF-8
<% content_for :lnks2 do %>
  | <%= link_to 'К концерту', edit_concert_path(@concert) %>
  | <%= link_to_function 'Записать', "$('input[name=commit]').first().click()" %>
  | <%= link_to '0', :root, title: 'Просмотр' %>
  |
<% end %>

<%= h1andcontent "Конструктор карусели, #{@concert.year}" %>

<%= render 'form' %>

app/views/carousels/show.html.erb
<% content_for :lnks2 do %>
  | <%= link_to 'К концерту', edit_concert_path(@concert) %>
  | <%= link_to 'К списку', concert_alboms_path %>
  | <%= link_to 'Новый', :new_concert_albom %>
  | <%= link_to 'Изменить', :edit_concert_albom %>
  | <%= link_to 'Удалить', concert_albom_path(@albom.concert, @albom), method: :delete, data: { confirm: 'Вы уверены что хотите удалить данного участника ? Он хороший.' } %>
  | <%= link_to '0', :root, title: 'Просмотр' %>
  |
<% end %>

<div style='font-family:arial;font-size:16px'>
  <p>
    <%= @albom.title %>
  </p>
  <div style="display:inline-block;margin-left:12px">
    <%= image_tag(@albom.fototitle.url) if @albom.fototitle.exists? %>
  </div>
  <div style="width:333px;display:inline-block;">
    <div>
      <%= @albom.text %>
    </div>
  </div>

  <p>
    <%= @albom.tumba %>
  </p>
</div>



<% @albom.fotos.each do |foto| %>
  <%= image_tag foto.image.url(:sm) %>
<% end %>