config/routes.rb
Dd::Application.routes.draw do


scope "(:locale)", locale: /ru|en/ do


  match '/ad', to: 'users#signin', via: :get

  resources :users do
    collection do
      get :signin
      post :signin, action: 'check'
      get :signout
    end
  end

  match '/news', to: 'news/feeds#list', via: :get #admin list of news
  
  namespace 'news' do
    resources :feeds do
      collection {get :tags}
      collection {post :tags_update}
      collection {post :insert_media}
    end
  end
 

  root to: 'pages#home'

  match '/help', to: 'pages#help', via: :get  #site
  match '/translation', to: 'pages#translation', via: :get  #admin
  match '/update_translation', to: 'pages#update_translation', via: :post  #admin

  match '/browser_detect', to: 'pages#browser_detect', via: :get #site
  match '/help_edit', to: 'pages#help_edit', via: :get  #admin
  match '/help_update', to: 'pages#help_update', via: [:put, :post] #admin
  match '/home_update', to: 'pages#home_update', via: [:post, :put] #admin
  match '/home_edit', to: 'pages#home_edit', via: :get  #admin


  match '/albom_c', to: 'alboms#gallery', via: :get #site
  match '/member_c', to: 'members_page#show', via: :get #site
  match '/concert_c', to: 'concerts#show', via: :get #site

  match '/concerts/alboms', to: 'concerts#alboms', via: :get #admin
  match '/concerts/members', to: 'concerts#members', via: :get #admin
  match '/concerts/partners', to: 'concerts#partners', via: :get #admin
  
  match '/update', to: 'alboms#update' #adim

  match 'home/:id', to: 'pages#home', as: :ura  #site, cycle by year in home page


resources :mailics do
  collection {post :captcha}
  collection {post :volunteer}
  collection {post :callback}
end


resources :flags, only: [:index, :create]

  # match 'contacts' =>       'contacts#index'
  # match 'contacts/edit' =>  'contacts#edit'
  # match 'contacts/creat' => 'contacts#creat', via: post
  # match 'contacts/text' =>  'contacts#tetx', via: post

  resources :contacts, only: [:index, :create, :edit] do
    collection {post :text}
    collection {get :edit}
  end

  resources :teams  #team of project

  resources :concerts do
    member {post :m_update}
    resources :members_page, only: [:show, :edit, :update] do #because has_one
      collection {get :page}
    end
    
    resources :carousels
    resources :members  #members each concert

    resources :partners do
      collection {post :global} # update who is for home page
    end

    resources :alboms do
      collection {get :gallery}
    end
    resources :videos
  end

  resources :fotos

end
end

app/models/news.rb
module News
  def self.table_name_prefix
    'news_'
  end
end

app/models/news/feed.rb
class News::Feed < ActiveRecord::Base
  attr_accessor :new_tag_name, :new_rubric_name
  attr_accessible :author, :date, :preambula, :text, :title, :foto
  translates :author, :preambula, :text, :title
  attr_accessible :new_tag_name, :tag_ids, :new_rubric_name, :rubric_ids

  has_attached_file :foto, styles: {original: "433x350>"} 

  before_save :create_rubric_tag

  has_many :feed_tags, uniq: true
  has_many :tags, through: :feed_tags, dependent: :destroy  
  has_many :feed_rubrics, uniq: true
  has_many :rubric, through: :feed_rubrics, dependent: :destroy
  #has_and_belongs_to_many :tags, uniq: true
  #has_and_belongs_to_many :rubric, uniq: true
  default_scope order('date DESC, id DESC')

  paginates_per 5


  def prev
    if News::Feed.first == self
      News::Feed.last
    else
      News::Feed.where('date > ? OR (date == ? AND id < ?)', date, date, id).last
    end
  end

  def next
    if News::Feed.last == self
      News::Feed.first
    else
      News::Feed.where('date < ? OR (date == ? AND id > ?)', date, date, id).first
    end

  end

  def create_rubric_tag
    
    unless new_tag_name.blank?
      if News::Tag.exists?(name: new_tag_name )
        tags << News::Tag.find_by_name( new_tag_name )
      else
        tags.create(name: new_tag_name)
      end
    end

    unless new_rubric_name.blank?
      if News::Rubric.exists?(name: new_rubric_name )
        rubric << News::Rubric.find_by_name(new_rubric_name )
      else
        rubric.create(name: new_rubric_name)
      end
    end

  end

end

app/models/news/feed_rubric.rb
class News::FeedRubric < ActiveRecord::Base
  belongs_to :feed
  belongs_to :rubric
  # attr_accessible :title, :body

  validates :feed, presence: true
  validates :rubric, presence: true

end

app/models/news/feed_tag.rb
class News::FeedTag < ActiveRecord::Base
  #attr_accessible :feed_id, :tag_id
  belongs_to :feed
  belongs_to :tag

  validates :feed, presence: true
  validates :tag, presence: true
end

app/models/news/rubric.rb
#encoding: UTF-8
class News::Rubric < ActiveRecord::Base
  attr_accessible :name, uniq: true
  translates :name
  
  has_many :feed_rubrics, dependent: :destroy
  has_many :feeds, through: :feed_rubrics
  #has_and_belongs_to_many :feeds#, dependent: :destroy
  default_scope order('name ASC')

  validates :name, presence: { message: "Ошибка, пустая строка"}
end

app/models/news/tag.rb
#encoding: UTF-8
class News::Tag < ActiveRecord::Base
  attr_accessible :name, uniq: true
  translates :name
  
  has_many :feed_tags, dependent: :destroy
  has_many :feeds, through: :feed_tags
  #has_and_belongs_to_many :feeds#, dependent: :destroy
  default_scope order('name ASC')

  validates :name, presence: { message: "Ошибка, пустая строка"}

end

app/controllers/news/feeds_controller.rb
#encoding: UTF-8
class News::FeedsController < ApplicationController
  before_filter :signed_in_user,  except: [:show, :list]


  layout 'dd', only: [:show, :list]

  def index
    @news = News::Feed.page(params[:p]).per(99)
  end

  def show  #user
    @url_to_edit = edit_news_feed_path
    @news = News::Feed.find(params[:id])
  end

  def list  #user
    # debugger
    @url_to_edit = news_feeds_path
    @news = News::Feed.includes(:tags, :rubric)
    if params[:t]
      @news = @news.joins(:feed_tags).where("tag_id IN (?)", params[:t]).uniq
    else
      params[:t] = []
    end

    if params[:r]
      @news = @news.joins(:feed_rubrics).where("rubric_id IN (?)", params[:r]).uniq
    else
      params[:r] = []
    end
      
    @news = @news.page params[:p]
  end
  

  def new
    @news = News::Feed.new
  end

  def tags
    @tags = News::Tag.all
    @rubric = News::Rubric.all
  end

  def tags_update

    if ( params.key? 'cancel' )
      notice = 'Восстановлены предыдущие данные'
    else
      d = ( params[:tag] || {} ).delete(:del)
      z = ( ( params[:tag] || {} )[:id] || {} ).delete('0')
      News::Tag.destroy(d.keys) unless d.blank?
      News::Tag.create(z) unless z.blank?
      @tags = !params[:tag].blank? ? News::Tag.update(params[:tag][:id].keys, params[:tag][:id].values) : []

      d = ( params[:rubric] || {} ).delete(:del)
      z = ( ( params[:rubric] || {} )[:id] || {} ).delete('0')
      News::Rubric.destroy(d.keys) unless d.blank?
      News::Rubric.create(z) unless z.blank?
      @rubric = !params[:tag].blank? ? News::Rubric.update(params[:rubric][:id].keys, params[:rubric][:id].values) : []
      notice = 'Обновлено'
    end

    # notice ? redirect_to(tags_news_feeds_path, notice: notice) : render(action: "edit")
    redirect_to tags_news_feeds_path(feed: params[:feed]), notice: notice

  end

  def insert_media
    @albom = Albom.find_by_id params[:media][:albom]
    @video = Video.find_by_id params[:media][:video]
    respond_to do |f|
      f.html
      f.js {}
    end
  end
  
  
  def edit
    @news = News::Feed.find(params[:id])
  end

  def create
    if ( params.key? 'cancel' )
      redirect_to :new_news_feed, notice: 'Данные сброшены'
    else
      @news = News::Feed.new(params[:news_feed])
      if @news.save
        redirect_to edit_news_feed_path(@news), notice: 'Новость создана'
      else
        render action: "new"
      end
    end

  end

  def update

    if ( params.key? 'cancel' )
      notice = 'Восстановлены предыдущие данные'
    else
      @news = News::Feed.find(params[:id])
      notice = 'Обновление прошло успешно' if @news.update_attributes(params[:news_feed])
    end

    notice ? redirect_to(edit_news_feed_path, notice: notice) : render(action: "edit")

  end

  def destroy

    @news = News::Feed.find(params[:id])
    @news.destroy

    redirect_to news_feeds_url
  end
end

app/helpers/news/feeds_helper.rb
module News::FeedsHelper
  
end

app/views/news/feeds/_feed.html.erb
<div class="inner-space">

  <div class="news">
    <div class="news-top">
      <div class="m-box-6">
        <%= link_to news_feed_path(feed) do %>
          <h5><span><%= feed.title %></span></h5>
        <% end %>
      </div>
      <div class="m-box-4">
        <div class="news-activity">
          <span class="date"><%= feed.date.strftime("%d/%m/%Y") %></span>
        </div>
      </div>
    </div>
    <div class="news-content">
      <div class="row">
        <div class="t-box-2">
          <%= raw feed.preambula %>
        </div>
        <div class="t-box-2">
          <div class="media-news">
            <%= link_to news_feed_path(feed) do %>
              <%= image_tag feed.foto.url %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="news-bottom">
      <div class="row">
        <div class="m-box-3">
          <div class="news-info">
            <div class="rubric"><%= t 'news.rubric' %>: 
              <% feed.rubric.each do |rubric| %>
                <%= tag_to_link rubric, 'r', 't', false %>
              <% end %>
            </div>
            <div class="tags"><%= t 'news.tags' %>: 
              <% feed.tags.each do |tag| %>
                <%= tag_to_link tag, 't', 'r', false %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="m-box-3">
          <div class="author"><%= t 'news.author' %>: 
            <span><%= feed.author %></span>
          </div>
        </div>
        <div class="m-box-3">
          <%= link_to t("news.detail"), news_feed_path(feed), class: "btn-red" %>
        </div>
      </div>
    </div>
  </div>

</div>

<div class="slice-block-gray"></div>

app/views/news/feeds/_form.html.erb
<style>

div.field{
  margin-bottom: 6px;
  width: 668px; 
}
.field input[type="number"]{
  width: 50px;
}
.field input{
  font-family: monospace;
  width: 548px; 
  float: right;
  margin-bottom: 12px;
}
</style>
<script>
  function send(){
      $.ajax({
          url: '<%= insert_media_news_feeds_path %>',
          data: $('#media_albom, #media_video').serialize(),
          dataType: "script",
          type: 'POST',
          success: function(data){ $('#notice').text('Сделано!').show().delay(5000).fadeOut('slow'); }});
      return false;
  }
</script>


<%= form_for @news, html: {multipart: true} do |f| %>

  <%= render partial: 'template/error', object: @news %>
  
  <div class="field">
    <%= f.label :title, "Заглавие" %>
    <%= f.text_field :title, placeholder: 'title' %>
  </div>
  <br/>
  <div class="field">
    <%= f.label :preambula, "Преамбула" %><br/>
    <%= f.text_area :preambula, rows_by_cols_and_content(@news.preambula, 80).merge(id: :ce_1, placeholder: 'preambula') %>
  </div>
  <div class="field">
    <%= f.label :text, "Основной текст" %><br/>
    <%= f.text_area :text, rows_by_cols_and_content(@news.text, 80).merge(id: :ce_2, placeholder: 'title', placeholder: 'main_text') %>
  </div>
    <%= collection_select :media, :albom, Albom.joins(:concert).reorder('year DESC'), :id, :year_title, prompt: 'Выбор альбома', name: :albom %>
    <%= collection_select :media, :video, Video.joins(:concert).reorder('year DESC'), :id, :year_title, prompt: 'Выбор видео' %>
      <%= link_to 'Вставить в основной текст', '', onclick: "send();return false;" %>
  <br/>
  <br/>


  <div class="field" style='display: inline-block; width: 444px'>
    <%= f.label :author, "Автор" %>
    <%= f.text_field :author, style: 'float:none; width: 288px', placeholder: 'author' %>
  </div>
  <div class="field" style="display: inline-block; width: 222px">
    <%= f.label :date, "Дата" %>
    <%= f.date_select :date, order: [:day,:month,:year], use_two_digit_numbers: true, placeholder: 'date' %>
  </div>

  <br/>

  <div class="field" style="display: inline-block; width: 111px">
    <span class='second_links'>
      <%= link_to "Тэги", tags_news_feeds_path( feed: @news.id ), class: :open %>
    </span>
    <br/>

    <%= f.collection_select :tag_ids, (News::Tag.all), :id, :name,{}, {multiple: true, size: 19, style: 'width:99px'} %><br/>
    <%= f.label :new_tag_name, "добавить" %><br/>
    <%= f.text_field :new_tag_name, style: "float: none; width: 95px", placeholder: 'new_tag' %>
    <div style="clear:both"></div>
  </div>
  <div class="field" style="display: inline-block; width: 111px">
    <span class='second_links'>
      <%= link_to "Рубрики",tags_news_feeds_path( feed: @news.id ), class: :open %>
    </span>
    <br/>
    <%= f.collection_select :rubric_ids, (News::Rubric.all), :id, :name,{}, {multiple: true, size: 19, style: 'width: 99px'} %><br/>
    <%= f.label :new_rubric_name, "добавить" %><br/>
    <%= f.text_field :new_rubric_name, style: "float: none; width: 95px", placeholder: 'new_rubric' %>
  </div>
  <div style="width: 400px; display: inline-block">
    <div class="field">
      <%= f.label :foto, "Фото", style: 'width: 44px' %>
      <%= f.file_field :foto, style: 'float: none', accept: "image/*" %>
    </div>
    <%= image_tag @news.foto.url if @news.foto.exists? %>
  </div>
  
</table>

  <div class="actions">
    <%= f.submit "Записать" %>
    <%= f.submit "Отмена", name: 'cancel' %> 
  </div>

<% end %>

<script>
  CKEDITOR.replace( 'ce_1' );
  CKEDITOR.replace( 'ce_2' );
</script>

app/views/news/feeds/_media.html.erb

<div class="media-blocks">
  <% unless @albom.blank? %>
    <div class="media-block">
      <%= link_to concert_albom_path(@albom.concert, @albom) do %>
        <%= image_tag @albom.url() %>
        <span class="album-mask">
          <%= content_tag :h6, @albom.title %>
          <%= content_tag :p, @albom.tumba %>
        </span>
      <% end %>
    </div>
  <% end %>
  <% unless @video.blank? %>
    <div class="media-block media-news">
      <%= link_to @video.link, class: "swipebox-vide hover-video", rel: :youtube do %>
        <%= image_tag @video.url() %>
        <span class="video-mask"></span>
      <% end %>
    </div>
  <% end %>
</div>

app/views/news/feeds/_show_paginator.html.erb
<div class="m-box-3">
  <div class="wrap-paginatior">
    <div class="inner-space">
      <div class="navigation">
        <ul>
          <li class="prev"><%= link_to '', @news.prev %></li>
          <li class="back"><%= link_to '', news_path %></li>
          <li class="next"><%= link_to '', @news.next %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/news/feeds/edit.html.erb
<% content_for :lnks2 do %>
  | <%= link_to 'К списку', :news_feeds %>
  | <%= link_to 'Удалить', news_feed_path(@news), method: :delete, data: { confirm: 'Вы уверены в удалении ?'} %>
  | <%= link_to_function 'Записать', "$('input[name=commit]').first().click()" %>
  | <%= link_to_function 'Отменить', "$('input[name=cancel]').first().click()" %>
  | <%= link_to 'Создать', :new_news_feed %>
  | <%= link_to '0', @news, title: 'Просмотр' %>
  |
<% end %>

<%= h1andcontent "Редактирование новости '#{@news.title}'" %>

<%= render 'form' %>

app/views/news/feeds/index.html.erb
<style>
  nav.pagination{
    padding-top: 12px;
    font-size: 14px;
    font-family: courier;
    padding-left: 256px;
  }
  nav.pagination a{
    padding-top: 12px;
    font-size: 14px;
    font-family: courier;
    background: #eee;
    font-weight: 700;
    padding: 0px 4px;
    margin-top: 3px;
  }
  nav.pagination a:hover{
    background: yellow;
  }
  #current {
    background: #ccf;
  }
</style>

<% content_for :lnks2 do %>
  | <%= link_to 'Новая', new_news_feed_path %>
  | <%= link_to 'Тэг/Рубрика', :tags_news_feeds %>
  | <%= link_to '0', :news, title: 'Просмотр' %>
  |
<% end %>

<%= h1andcontent "Новости (#{@news.count}/#{News::Feed.count})" %>

<%= paginate @news %> 
<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @news.each do |news| %>
  <tr>
    <td><b><%= news.date.strftime( "%d.%m.%y" ) %></b></td>
    <td><%= news.title %></td>
    <td>
      <%= link_to 'Просмотр', news %> |
      <%= link_to 'Изменить', edit_news_feed_path(news) %> |
      <%= link_to 'Удалить', news_feed_path(news), method: :delete, data: { confirm: 'Вы уверены в удалении ?' } %>
    </td>
  </tr>
<% end %>
</table>

<%= paginate @news %> 

app/views/news/feeds/insert_media.js.erb
  var editor = CKEDITOR.instances.ce_2;
  if ( editor.mode == 'wysiwyg' ) {
    editor.insertHtml( '<%= j(render(partial: "media")) %>', "unfiltered_html" ); }
  else
    alert( 'Вы должны быть в WYSIWYG режиме!' );


  

app/views/news/feeds/list.html.erb
<% provide(:title, t('global.title')) %>

<div class="news-page-content">
  <div class="container">
    <div class="top-info-content">

      <div class="inner-space">
        <h1><%= t 'news.news' %></h1>
      </div>

    </div>
    <div class="p-news">

      <div class="inner-space">
        <div class="news-nav">

          <div class="row">
            <div class="m-box-2">
              <ul><span><%= t 'news.tags' %>:</span>
                <%= content_tag :li, link_to('', r: params[:r]), class: "delete#{' active' if params[:t]==[]}" %>
                <% News::Tag.all.each do |tag| %>
                  <li>
                    <%= tag_to_link tag, 't', 'r' %>
                  </li>
                <% end %>
              </ul>
            </div>
            <div class="m-box-2">
              <ul><span><%= t 'news.rubric' %>:</span>
                <%= content_tag :li, link_to("", t: params[:t]), class: "delete#{' active' if params[:r]==[]}" %>
                <% News::Rubric.all.each do |rubric| %>
                  <li>
                    <%= tag_to_link rubric, 'r', 't' %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>

        </div>

        <div class="news-line">
          <span><i></i></span>
        </div>
      </div>


      <%= render @news %>


      <div class="triangle-gray-up"></div>
      <div class="wrap-paginatior">
        <div class="inner-space">
          <%= paginate @news, theme: 'vovan' %> 
        </div>
      </div>
    </div>
  </div>
</div>

app/views/news/feeds/new.html.erb
<% content_for :lnks2 do %>
  | <%= link_to_function 'Записать', "$('input[name=commit]').first().click()" %>
  | <%= link_to_function 'Сбросить', "$('input[name=cancel]').first().click()" %>
  | <%= link_to 'К списку', :news_feeds %>
  | <%= link_to '0', @news, title: 'Просмотр' %>
  |
<% end %>

<%= h1andcontent "Создание новости" %>

<%= render 'form' %>

app/views/news/feeds/show.html.erb
<% provide(:title, t('global.title')) %>

<div class="news-inner-content">
  <div class="container">

    <div class="top-info-content">
      <div class="inner-space">
        <h2><%= @news.title %></h2>
      </div>
      <div class="triangle-gray-up"></div>
    </div>

    <div class="p-news-inner">
      <div class="inner-space">
        <div class="news">
          <div class="news-content">

            <div class="top-news-content">
              <div class="row">
                <div class="t-box-2">
                  <%= raw @news.preambula %>
                </div>
                <div class="t-box-2">
                  <div class="">
                    <%= image_tag @news.foto.url %>
                  </div>
                </div>
              </div>
            </div>

            <%= raw @news.text %>

          </div>

          <div class="news-bottom">
            <div class="row">

              <div class="m-box-3">
                <div class="news-info">
                  <div class="rubric"><%= t 'news.rubric' %>:
                    <% @news.rubric.each do |rubric| %>
                      <%= link_to rubric.name, news_path('r[]' => "#{rubric.id}") %>
                    <% end %>
                  </div>
                  <div class="tags"><%= t 'news.tags' %>: 
                    <% @news.tags.each do |tag| %>
                      <%= link_to tag.name, news_path('t[]' => "#{tag.id}") %>
                    <% end %>
                  </div>
                </div>
              </div>

              <%= render 'show_paginator' %>

              <div class="m-box-3">
                <div class="m-box-6">
                  <div class="author"><%= t 'news.author' %>: 
                    <span><%= @news.author %></span>
                  </div>
                </div>
                <div class="m-box-4">
                  <span class="date">
                    <%= @news.date.strftime('%d/%m/%Y') %>
                  </span>
                </div>
              </div>
            </div>
          </div>
          
        </div>
      </div>
    </div>
  </div>
</div>

app/views/news/feeds/tags.html.erb

<style>
  td {
    vertical-align:top;
    padding: 10px 30px;
  }
  input[type='text'] {
    width: 150px;
    margin-right: 5px;
    font-family: monospace;
  }
  a.link_add {
    float: right;
    margin-top: 16px;
  }
</style>

<% content_for :lnks2 do %>
  <% if params.key?(:feed) %>
    | <%= link_to( 'Вернуться к новости', edit_news_feed_path(params[:feed]) ) %>
  <% end %>
  | <%= link_to_function 'Записать', "$('input[name=commit]').first().click()" %>
  | <%= link_to_function 'Отменить', "$('input[name=cancel]').first().click()" %>
  | <%= link_to_function '+тэг', "$('#tag_link').first().click()" %>
  | <%= link_to_function '+рубрика', "$('#rubric_link').first().click()" %>
  | <%= link_to 'Новости', :news_feeds %>
  | <%= link_to '0', :news, title: 'Просмотр' %>
  |
<% end %>


<%= h1andcontent "Тэги (#{@tags.count}) и Рубрики (#{@rubric.count})" %>

<%= form_tag tags_update_news_feeds_path(feed: params[:feed]) do %>
  
  <table>
    <tr>
      <td>

        <div class='fields'>
          <% @tags.each do |i| %>
            <div class='f'>
              <% #debugger %>
              <%= fields_for "tag[id][#{i.id}]", i do |tt| %>
                Тэг: <%= tt.text_field :name, placeholder: i.name %>
                <%= link_to_function "Удалить", 'hide_tag(this)'%>
                <br/>
              <% end %>
            </div>
          <% end %>
          <%= link_to_function "Добавить", "add_tag(this, 'Тэг', 'tag')", class: :link_link, id: :tag_link %>
        </div>
      </td>

      <td>
        <div class='fields'>
          <% @rubric.each do |i| %>
            <div class='f'>
              <%= fields_for "rubric[id][#{i.id}]", i do |tt| %>
                Рубрика: <%= tt.text_field :name %>
                <%= link_to_function "Удалить", 'hide_tag(this)'%>
                <br/>
              <% end %>
            </div>
          <% end %>
          <%= link_to_function "Добавить", "add_tag(this, 'Рубрика', 'rubric')", class: :link_add, id: :rubric_link %>
        </div>
      </td>
    </tr>
  </table>

  <%= submit_tag "Обновить" %>
  <%= submit_tag "Отмена", name: 'cancel' %>
  
<% end %>


