config/routes.rb
Dd::Application.routes.draw do


scope "(:locale)", locale: /ru|en/ do


  match '/ad', to: 'users#signin', via: :get

  resources :users do
    collection do
      get :signin
      post :signin, action: 'check'
      get :signout
    end
  end

  match '/news', to: 'news/feeds#list', via: :get #admin list of news
  
  namespace 'news' do
    resources :feeds do
      collection {get :tags}
      collection {post :tags_update}
      collection {post :insert_media}
    end
  end
 

  root to: 'pages#home'

  match '/help', to: 'pages#help', via: :get  #site
  match '/translation', to: 'pages#translation', via: :get  #admin
  match '/update_translation', to: 'pages#update_translation', via: :post  #admin

  match '/browser_detect', to: 'pages#browser_detect', via: :get #site
  match '/help_edit', to: 'pages#help_edit', via: :get  #admin
  match '/help_update', to: 'pages#help_update', via: [:put, :post] #admin
  match '/home_update', to: 'pages#home_update', via: [:post, :put] #admin
  match '/home_edit', to: 'pages#home_edit', via: :get  #admin


  match '/albom_c', to: 'alboms#gallery', via: :get #site
  match '/member_c', to: 'members_page#show', via: :get #site
  match '/concert_c', to: 'concerts#show', via: :get #site

  match '/concerts/alboms', to: 'concerts#alboms', via: :get #admin
  match '/concerts/members', to: 'concerts#members', via: :get #admin
  match '/concerts/partners', to: 'concerts#partners', via: :get #admin
  
  match '/update', to: 'alboms#update' #adim

  match 'home/:id', to: 'pages#home', as: :ura  #site, cycle by year in home page


resources :mailics do
  collection {post :captcha}
  collection {post :volunteer}
  collection {post :callback}
end


resources :flags, only: [:index, :create]

  # match 'contacts' =>       'contacts#index'
  # match 'contacts/edit' =>  'contacts#edit'
  # match 'contacts/creat' => 'contacts#creat', via: post
  # match 'contacts/text' =>  'contacts#tetx', via: post

  resources :contacts, only: [:index, :create, :edit] do
    collection {post :text}
    collection {get :edit}
  end

  resources :teams  #team of project

  resources :concerts do
    member {post :m_update}
    resources :members_page, only: [:show, :edit, :update] do #because has_one
      collection {get :page}
    end
    
    resources :carousels
    resources :members  #members each concert

    resources :partners do
      collection {post :global} # update who is for home page
    end

    resources :alboms do
      collection {get :gallery}
    end
    resources :videos
  end

  resources :fotos

end
end

app/models/video.rb
#encoding: UTF-8
class Video < ActiveRecord::Base
  belongs_to :concert
  has_many :carousels, dependent: :destroy
  attr_accessible :foto, :link, :title
  translates :title
  has_attached_file :foto, styles: {original: "433x350>", sm: "64x64>", carousel: "280x247"} #280x247

  validates :link, presence: { message: 'Ссылка обязательна' }

  before_save :check_link 

  def url(arg = :original)
    foto.url(arg)
  end

  def year_title
    concert.year.to_s + ' ' + title
  end
  
  def check_link  #add http to link if not
    return self.link = '' if self.link.size < 3
    self.link = 'http://' + self.link unless self.link.match( /\Ahttp[s]?:\/\// )
  end


end

app/controllers/videos_controller.rb
#endcoding: UTF-8
class VideosController < ApplicationController
  before_filter :signed_in_user
  include ApplicationHelper  
  
  def index

    @concert = Concert.find(params[:concert_id])
    @videos = @concert.videos
  end
  
  def show
    @video = Concert.find(params[:concert_id]).videos.find(params[:id])
  end
  
  def new
    @video = Concert.find(params[:concert_id]).videos.build
  end
  
  def edit
    @video = Concert.find(params[:concert_id]).videos.find(params[:id])
  end

  def create
    @video = Concert.find(params[:concert_id]).videos.build(params[:video])

    if @video.save
      redirect_to concert_videos_path(@video.concert), notice: 'Успешное создание ссылки'
    else
      render action: "new"
    end
  end

  def update
    @video = Concert.find(params[:concert_id]).videos.find(params[:id])

    if @video.update_attributes(params[:video])
      redirect_to concert_videos_path(@video.concert), notice: 'Ссылка успешно обновлена'
    else
      render action: "edit"
    end
  end

  def destroy
    @video = Concert.find(params[:concert_id]).videos.find(params[:id])
    redirect_to concert_videos_url, notice: "Удалена ссылка #{remove_http(@video.destroy.link)}"
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_for([@video.concert, @video]) do |f| %>

  <%= render partial: 'template/error', object: @video %>

  <div class="field">
    <%= f.label :link, 'Ссылка' %><br />
    <%= f.text_field :link, value: remove_http(@video.link), size: 49, required: true, placeholder: 'link' %>
  </div>  
  <div class="field">
    <%= f.label :title, 'Название' %><br />
    <%= f.text_field :title, size: 49, required: true, placeholder: 'title' %>
  </div>
  <br/>
  <div class="field">
    <%= f.label :foto, 'Обложка' %>
    <%= f.file_field :foto %>
  </div>

  <%= image_tag @video.foto.url if @video.foto.exists? %>

  <br/><br/>
    
  <div class="actions">
    <%= f.submit "Обновить информацию" %>
  </div>
<% end %>

app/views/videos/_video.html.erb
<%= raw '<div class="row">' if video_counter % 3 == 0 %>
  <div class="t-box-3 album-thumb">
    <%= link_to video.link, rel: :youtube, class: 'swipebox-video hover-video' do %>
      <%= image_tag video.foto.url %>
      <span class="video-mask"></span>
    <% end %>
  </div>
<%= raw '</div>' if video_counter % 3 == 2 %>

app/views/videos/edit.html.erb
<% content_for :lnks2 do %>
  | <%= link_to 'К концерту', edit_concert_path(@video.concert) %>
  | <%= link_to 'Просмотр', [@video.concert, @video] %>
  | <%= link_to 'К списку', concert_videos_path(@video.concert) %>
  | <%= link_to 'Новая', new_concert_video_path(@video.concert,@video), data: {confirm: 'Несохраненные данные будут утеряны, Да ?'} %>
  | <%= link_to 'Удалить', concert_video_path(@video.concert, @video), method: :delete, data: { confirm: 'Вы уверены что хотите удалить данную ссылку ?' } %>
  | <%= link_to_function 'Записать', "$('input[name=commit]').first().click()" %>
  |
<% end %>

<%= h1andcontent "Редактирование видео #{@video.title}, #{@video.concert.year}" %>

<%= render 'form' %>

app/views/videos/index.html.erb
<% content_for :lnks2 do %>
  | <%= link_to 'К концерту', edit_concert_path(@concert) %>
  | <%= link_to 'Просмотр', gallery_concert_alboms_path(@concert) %>
  | <%= link_to 'Новая', new_concert_video_path %>
  | <%= link_to 'Альбомы', concert_alboms_path(@concert) %>
  |
<% end %>

<%= h1andcontent "Ссылки на видео (#{@videos.count}), #{@concert.year}" %>

<table>
  <tr>
    <th width="80px"></th>
    <th></th>
    <th width="150px"></th>
    <th></th>
  </tr>

<% @videos.each do |video| %>
  <tr height='65px'>
    <td><%= link_to (image_tag video.foto.url(:sm)), [video.concert, video], class: :link_image %></td>
    <td>
      <b><%= video.title %></b>
    </td>
    <td>
      <%= link_to remove_http(video.link), video.link, target: "_blank" %>
    </td>    
    <td>
      <%= link_to 'Просмотреть', [video.concert, video] %> |
      <%= link_to 'Изменить', edit_concert_video_path(video.concert, video) %> |
      <%= link_to 'Удалить', [video.concert, video], method: :delete, data: { confirm: 'Уверены ?' } %></td>
    </tr>
  </tr>
<% end %>
</table>

app/views/videos/new.html.erb
<% content_for :lnks2 do %>
  | <%= link_to 'К концерту', edit_concert_path(@video.concert) %>
  | <%= link_to 'К списку', concert_videos_path(@video.concert) %>
  | <%= link_to_function 'Записать', "$('input[name=commit]').first().click()" %>
  |
<% end %>

<%= h1andcontent "Новая ссылка на видео, #{@video.concert.year}" %>

<%= render 'form' %>

app/views/videos/show.html.erb
<% content_for :lnks2 do %>
  | <%= link_to 'К концерту', edit_concert_path(@video.concert) %>
  | <%= link_to 'К списку', concert_videos_path(@video.concert) %>
  | <%= link_to 'Новая', new_concert_video_path(@video.concert) %>
  | <%= link_to 'Удалить', concert_video_path(@video.concert, @video), method: :delete, data: { confirm: 'Вы уверены что хотите удалить данную ссылку ?' } %>
  |
<% end %>
<%= h1andcontent "Ссылка видео #{@video.title}, #{@video.concert.year}" %>
<div class='box'>
  <p>
    <b><%= @video.title %></b>
  <p>
    <%= link_to_unless @video.link.blank?, remove_http(@video.link), @video.link %>
  </p>
  <p>
    <%= image_tag @video.foto.url if @video.foto.exists? %>
  </p>
</div>